import random
import time
import webbrowser

random.seed(time.time())

# Episodes

TOSepisodes = [
   'S0E01 The Cage',
   'S0E02 Where No Man Has Gone Before',
   'S1E01 The Man Trap',
   'S1E02 Charlie X',
   'S1E03 Where No Man Has Gone Before',
   'S1E04 The Naked Time',
   'S1E05 The Enemy Within',
   'S1E06 Mudds Women',
   'S1E07 What Are Little Girls Made Of?',
   'S1E08 Miri',
   'S1E09 Dagger of the Mind',
   'S1E10 The Corbomite Maneuver',
   'S1E11 The Menagerie Part I',
   'S1E12 The Menagerie Part II',
   'S1E13 The Conscience of the King',
   'S1E14 Balance of Terror',
   'S1E15 Shore Leave',
   'S1E16 The Galileo Seven',
   'S1E17 The Squire of Gothos',
   'S1E18 Arena',
   'S1E19 Tomorrow Is Yesterday',
   'S1E20 Court Martial',
   'S1E21 The Return of the Archons',
   'S1E22 Space Seed',
   'S1E23 A Taste of Armageddon',
   'S1E24 This Side of Paradise',
   'S1E25 The Devil in the Dark',
   'S1E26 Errand of Mercy',
   'S1E27 The Alternative Factor',
   'S1E28 The City on the Edge of Forever',
   'S1E29 Operation -- Annihilate!',
   'S2E01 Amok Time',
   'S2E02 Who Mourns for Adonais?',
   'S2E03 The Changeling',
   'S2E04 Mirror, Mirror',
   'S2E05 The Apple',
   'S2E06 The Doomsday Machine',
   'S2E07 Catspaw',
   'S2E08 I, Mudd',
   'S2E09 Metamorphosis',
   'S2E10 Journey to Babel',
   'S2E11 Fridays Child',
   'S2E12 The Deadly Years',
   'S2E13 Obsession',
   'S2E14 Wolf in the Fold',
   'S2E15 The Trouble with Tribbles',
   'S2E16 The Gamesters of Triskelion',
   'S2E17 A Piece of the Action',
   'S2E18 The Immunity Syndrome',
   'S2E19 A Private Little War',
   'S2E20 Return to Tomorrow',
   'S2E21 Patterns of Force',
   'S2E22 By Any Other Name',
   'S2E23 The Omega Glory',
   'S2E24 The Ultimate Computer',
   'S2E25 Bread and Circuses',
   'S2E26 Assignment: Earth',
   'S3E01 Spocks Brain',
   'S3E02 The Enterprise Incident',
   'S3E03 The Paradise Syndrome',
   'S3E04 And the Children Shall Lead',
   'S3E05 Is There in Truth No Beauty?',
   'S3E06 Spectre of the Gun',
   'S3E07 Day of the Dove',
   'S3E08 For the World Is Hollow and I Have Touched the Sky',
   'S3E09 The Tholian Web',
   'S3E10 Platos Stepchildren',
   'S3E11 Wink of an Eye',
   'S3E12 The Empath',
   'S3E13 Elaan of Troyius',
   'S3E14 Whom Gods Destroy',
   'S3E15 Let That Be Your Last Battlefield',
   'S3E16 The Mark of Gideon',
   'S3E17 That Which Survives',
   'S3E18 The Lights of Zetar',
   'S3E19 Requiem for Methuselah',
   'S3E20 The Way to Eden',
   'S3E21 The Cloud Minders',
   'S3E22 The Savage Curtain',
   'S3E23 All Our Yesterdays',
   'S3E24 Turnabout Intruder',
]

TNGepisodes = [
   'S1E01 Encounter at Farpoint Part I',
   'S1E02 Encounter at Farpoint Part II',
   'S1E03 The Naked Now',
   'S1E04 Code of Honor',
   'S1E05 The Last Outpost',
   'S1E06 Where No One Has Gone Before',
   'S1E07 Lonely Among Us',
   'S1E08 Justice',
   'S1E09 The Battle',
   'S1E10 Hide and Q',
   'S1E11 Haven',
   'S1E12 The Big Goodbye',
   'S1E13 Datalore',
   'S1E14 Angel One',
   'S1E15 11001001',
   'S1E16 Too Short a Season',
   'S1E17 When the Bough Breaks',
   'S1E18 Home Soil',
   'S1E19 Coming of Age',
   'S1E20 Heart of Glory',
   'S1E21 The Arsenal of Freedom',
   'S1E22 Symbiosis',
   'S1E23 Skin of Evil',
   'S1E24 Well Always Have Paris',
   'S1E25 Conspiracy',
   'S1E26 The Neutral Zone',
   'S2E01 The Child',
   'S2E02 Where Silence Has Lease',
   'S2E03 Elementary, Dear Data',
   'S2E04 The Outrageous Okona',
   'S2E05 Loud as a Whisper',
   'S2E06 The Schizoid Man',
   'S2E07 Unnatural Selection',
   'S2E08 A Matter of Honor',
   'S2E09 The Measure of a Man',
   'S2E10 The Dauphin',
   'S2E11 Contagion',
   'S2E12 The Royale',
   'S2E13 Time Squared',
   'S2E14 The Icarus Factor',
   'S2E15 Pen Pals',
   'S2E16 Q Who',
   'S2E17 Samaritan Snare',
   'S2E18 Up the Long Ladder',
   'S2E19 Manhunt',
   'S2E20 The Emissary',
   'S2E21 Peak Performance',
   'S2E22 Shades of Gray',
   'S3E01 Evolution',
   'S3E02 The Ensigns of Command',
   'S3E03 The Survivors',
   'S3E04 Who Watches the Watchers',
   'S3E05 The Bonding',
   'S3E06 Booby Trap',
   'S3E07 The Enemy',
   'S3E08 The Price',
   'S3E09 The Vengeance Factor',
   'S3E10 The Defector',
   'S3E11 The Hunted',
   'S3E12 The High Ground',
   'S3E13 Deja Q',
   'S3E14 A Matter of Perspective',
   'S3E15 Yesterdays Enterprise',
   'S3E16 The Offspring',
   'S3E17 Sins of the Father',
   'S3E18 Allegiance',
   'S3E19 Captains Holiday',
   'S3E20 Tin Man',
   'S3E21 Hollow Pursuits',
   'S3E22 The Most Toys',
   'S3E23 Sarek',
   'S3E24 Ménage à Troi',
   'S3E25 Transfigurations',
   'S3E26 The Best of Both Worlds, Part I',
   'S4E01 The Best of Both Worlds, Part II',
   'S4E02 Family',
   'S4E03 Brothers',
   'S4E04 Suddenly Human',
   'S4E05 Remember Me',
   'S4E06 Legacy',
   'S4E07 Reunion',
   'S4E08 Future Imperfect',
   'S4E09 Final Mission',
   'S4E10 The Loss',
   'S4E11 Datas Day',
   'S4E12 The Wounded',
   'S4E13 Devils Due',
   'S4E14 Clues',
   'S4E15 First Contact',
   'S4E16 Galaxys Child',
   'S4E17 Night Terrors',
   'S4E18 Identity Crisis',
   'S4E19 The Nth Degree',
   'S4E20 Qpid',
   'S4E21 The Drumhead',
   'S4E22 Half a Life',
   'S4E23 The Host',
   'S4E24 The Minds Eye',
   'S4E25 In Theory',
   'S4E26 Redemption, Part I',
   'S5E01 Redemption, Part II',
   'S5E02 Darmok',
   'S5E03 Ensign Ro',
   'S5E04 Silicon Avatar',
   'S5E05 Disaster',
   'S5E06 The Game',
   'S5E07 Unification, Part I',
   'S5E08 Unification, Part II',
   'S5E09 A Matter of Time',
   'S5E10 New Ground',
   'S5E11 Hero Worship',
   'S5E12 Violations',
   'S5E13 The Masterpiece Society',
   'S5E14 Conundrum',
   'S5E15 Power Play',
   'S5E16 Ethics',
   'S5E17 The Outcast',
   'S5E18 Cause and Effect',
   'S5E19 The First Duty',
   'S5E20 Cost of Living',
   'S5E21 The Perfect Mate',
   'S5E22 Imaginary Friend',
   'S5E23 I, Borg',
   'S5E24 The Next Phase',
   'S5E25 The Inner Light',
   'S5E26 Times Arrow, Part I',
   'S6E01 Times Arrow, Part II',
   'S6E02 Realm of Fear',
   'S6E03 Man of the People',
   'S6E04 Relics',
   'S6E05 Schisms',
   'S6E06 True Q',
   'S6E07 Rascals',
   'S6E08 A Fistful of Datas',
   'S6E09 The Quality of Life',
   'S6E10 Chain of Command, Part I',
   'S6E11 Chain of Command, Part II',
   'S6E12 Ship in a Bottle',
   'S6E13 Aquiel',
   'S6E14 Face of the Enemy',
   'S6E15 Tapestry',
   'S6E16 Birthright, Part I',
   'S6E17 Birthright, Part II',
   'S6E18 Starship Mine',
   'S6E19 Lessons',
   'S6E20 The Chase',
   'S6E21 Frame of Mind',
   'S6E22 Suspicions',
   'S6E23 Rightful Heir',
   'S6E24 Second Chances',
   'S6E25 Timescape',
   'S6E26 Descent, Part I',
   'S7E01 Descent, Part II',
   'S7E02 Liaisons',
   'S7E03 Interface',
   'S7E04 Gambit, Part I',
   'S7E05 Gambit, Part II',
   'S7E06 Phantasms',
   'S7E07 Dark Page',
   'S7E08 Attached',
   'S7E09 Force of Nature',
   'S7E10 Inheritance',
   'S7E11 Parallels',
   'S7E12 The Pegasus',
   'S7E13 Homeward',
   'S7E14 Sub Rosa',
   'S7E15 Lower Decks',
   'S7E16 Thine Own Self',
   'S7E17 Masks',
   'S7E18 Eye of the Beholder',
   'S7E19 Genesis',
   'S7E20 Journeys End',
   'S7E21 Firstborn',
   'S7E22 Bloodlines',
   'S7E23 Emergence',
   'S7E24 Preemptive Strike',
   'S7E25 All Good Things... Part I',
   'S7E26 All Good Things... Part II',
]

DSNepisodes = [
   'S1E01 Emissary Part I',
   'S1E02 Emissary Part II',
   'S1E03 Past Prologue',
   'S1E04 A Man Alone',
   'S1E05 Babel',
   'S1E06 Captive Pursuit',
   'S1E07 Q-Less',
   'S1E08 Dax',
   'S1E09 The Passenger',
   'S1E10 Move Along Home',
   'S1E11 The Nagus',
   'S1E12 Vortex',
   'S1E13 Battle Lines',
   'S1E14 The Storyteller',
   'S1E15 Progress',
   'S1E16 If Wishes Were Horses',
   'S1E17 The Forsaken',
   'S1E18 Dramatis Personae',
   'S1E19 Duet',
   'S1E20 In the Hands of the Prophets',
   'S2E01 The Homecoming',
   'S2E02 The Circle',
   'S2E03 The Siege',
   'S2E04 Invasive Procedures',
   'S2E05 Cardassians',
   'S2E06 Melora',
   'S2E07 Rules of Acquisition',
   'S2E08 Necessary Evil',
   'S2E09 Second Sight',
   'S2E10 Sanctuary',
   'S2E11 Rivals',
   'S2E12 The Alternate',
   'S2E13 Armageddon Game',
   'S2E14 Whispers',
   'S2E15 Paradise',
   'S2E16 Shadowplay',
   'S2E17 Playing God',
   'S2E18 Profit and Loss',
   'S2E19 Blood Oath',
   'S2E20 The Maquis, Part I',
   'S2E21 The Maquis, Part II',
   'S2E22 The Wire',
   'S2E23 Crossover',
   'S2E24 The Collaborator',
   'S2E25 Tribunal',
   'S2E26 The JemHadar',
   'S3E01 The Search, Part I',
   'S3E02 The Search, Part II',
   'S3E03 The House of Quark',
   'S3E04 Equilibrium',
   'S3E05 Second Skin',
   'S3E06 The Abandoned',
   'S3E07 Civil Defense',
   'S3E08 Meridian',
   'S3E09 Defiant',
   'S3E10 Fascination',
   'S3E11 Past Tense, Part I',
   'S3E12 Past Tense, Part II',
   'S3E13 Life Support',
   'S3E14 Heart of Stone',
   'S3E15 Destiny',
   'S3E16 Prophet Motive',
   'S3E17 Visionary',
   'S3E18 Distant Voices',
   'S3E19 Through the Looking Glass',
   'S3E20 Improbable Cause',
   'S3E21 The Die Is Cast',
   'S3E22 Explorers',
   'S3E23 Family Business',
   'S3E24 Shakaar',
   'S3E25 Facets',
   'S3E26 The Adversary',
   'S4E01 The Way of the Warrior Part I',
   'S4E02 The Way of the Warrior Part II',
   'S4E02 The Visitor',
   'S4E03 Hippocratic Oath',
   'S4E04 Indiscretion',
   'S4E05 Rejoined',
   'S4E06 Starship Down',
   'S4E07 Little Green Men',
   'S4E08 The Sword of Kahless',
   'S4E09 Our Man Bashir',
   'S4E10 Homefront',
   'S4E11 Paradise Lost',
   'S4E12 Crossfire',
   'S4E13 Return to Grace',
   'S4E14 Sons of Mogh',
   'S4E15 Bar Association',
   'S4E16 Accession',
   'S4E17 Rules of Engagement',
   'S4E18 Hard Time',
   'S4E19 Shattered Mirror',
   'S4E20 The Muse',
   'S4E21 For the Cause',
   'S4E22 To the Death',
   'S4E23 The Quickening',
   'S4E24 Body Parts',
   'S4E25 Broken Link',
   'S5E01 Apocalypse Rising',
   'S5E02 The Ship',
   'S5E03 Looking for parMach in All the Wrong Places',
   'S5E04 ...Nor the Battle to the Strong',
   'S5E05 The Assignment',
   'S5E06 Trials and Tribble-ations',
   'S5E07 Let He Who Is Without Sin...',
   'S5E08 Things Past',
   'S5E09 The Ascent',
   'S5E10 Rapture',
   'S5E11 The Darkness and the Light',
   'S5E12 The Begotten',
   'S5E13 For the Uniform',
   'S5E14 In Purgatorys Shadow',
   'S5E15 By Infernos Light',
   'S5E16 Doctor Bashir, I Presume?',
   'S5E17 A Simple Investigation',
   'S5E18 Business as Usual',
   'S5E19 Ties of Blood and Water',
   'S5E20 Ferengi Love Songs',
   'S5E21 Soldiers of the Empire',
   'S5E22 Children of Time',
   'S5E23 Blaze of Glory',
   'S5E24 Empok Nor',
   'S5E25 In the Cards',
   'S5E26 Call to Arms',
   'S6E01 A Time to Stand',
   'S6E02 Rocks and Shoals',
   'S6E03 Sons and Daughters',
   'S6E04 Behind the Lines',
   'S6E05 Favor the Bold',
   'S6E06 Sacrifice of Angels',
   'S6E07 You Are Cordially Invited',
   'S6E08 Resurrection',
   'S6E09 Statistical Probabilities',
   'S6E10 The Magnificent Ferengi',
   'S6E11 Waltz',
   'S6E12 Who Mourns for Morn?',
   'S6E13 Far Beyond the Stars',
   'S6E14 One Little Ship',
   'S6E15 Honor Among Thieves',
   'S6E16 Change of Heart',
   'S6E17 Wrongs Darker Than Death or Night',
   'S6E18 Inquisition',
   'S6E19 In the Pale Moonlight',
   'S6E20 His Way',
   'S6E21 The Reckoning',
   'S6E22 Valiant',
   'S6E23 Profit and Lace',
   'S6E24 Times Orphan',
   'S6E25 The Sound of Her Voice',
   'S6E26 Tears of the Prophets',
   'S7E01 Image in the Sand',
   'S7E02 Shadows and Symbols',
   'S7E03 Afterimage',
   'S7E04 Take Me Out to the Holosuite',
   'S7E05 Chrysalis',
   'S7E06 Treachery, Faith and the Great River',
   'S7E07 Once More unto the Breach',
   'S7E08 The Siege of AR-558',
   'S7E09 Covenant',
   'S7E10 Its Only a Paper Moon',
   'S7E11 Prodigal Daughter',
   'S7E12 The Emperors New Cloak',
   'S7E13 Field of Fire',
   'S7E14 Chimera',
   'S7E15 Badda-Bing Badda-Bang',
   'S7E16 Inter Arma Enim Silent Leges',
   'S7E17 Penumbra',
   'S7E18 Til Death Do Us Part',
   'S7E19 Strange Bedfellows',
   'S7E20 The Changing Face of Evil',
   'S7E21 When It Rains...',
   'S7E22 Tacking into the Wind',
   'S7E23 Extreme Measures',
   'S7E24 The Dogs of War',
   'S7E25 What You Leave Behind Part I',
   'S7E26 What You Leave Behind Part II',
]

Vepisodes = [
   'S1E01 Caretaker Part I',
   'S1E02 Caretaker Part II',
   'S1E03 Parallax',
   'S1E04 Time and Again',
   'S1E05 Phage',
   'S1E06 The Cloud',
   'S1E07 Eye of the Needle',
   'S1E08 Ex Post Facto',
   'S1E09 Emanations',
   'S1E10 Prime Factors',
   'S1E11 State of Flux',
   'S1E12 Heroes and Demons',
   'S1E13 Cathexis',
   'S1E14 Faces',
   'S1E15 Jetrel',
   'S1E16 Learning Curve',
   'S2E01 The 37s',
   'S2E02 Initiations',
   'S2E03 Projections',
   'S2E04 Elogium',
   'S2E05 Non Sequitur',
   'S2E06 Twisted',
   'S2E07 Parturition',
   'S2E08 Persistence of Vision',
   'S2E09 Tattoo',
   'S2E10 Cold Fire',
   'S2E11 Maneuvers',
   'S2E12 Resistance',
   'S2E13 Prototype',
   'S2E14 Alliances',
   'S2E15 Threshold',
   'S2E16 Meld',
   'S2E17 Dreadnought',
   'S2E18 Death Wish',
   'S2E19 Lifesigns',
   'S2E20 Investigations',
   'S2E21 Deadlock',
   'S2E22 Innocence',
   'S2E23 The Thaw',
   'S2E24 Tuvix',
   'S2E25 Resolutions',
   'S2E26 Basics, Part I',
   'S3E01 Basics, Part II',
   'S3E02 Flashback',
   'S3E03 The Chute',
   'S3E04 The Swarm',
   'S3E05 False Profits',
   'S3E06 Remember',
   'S3E07 Sacred Ground',
   'S3E08 Futures End, Part I',
   'S3E09 Futures End, Part II',
   'S3E10 Warlord',
   'S3E11 The Q and the Grey',
   'S3E12 Macrocosm',
   'S3E13 Fair Trade',
   'S3E14 Alter Ego',
   'S3E15 Coda',
   'S3E16 Blood Fever',
   'S3E17 Unity',
   'S3E18 Darkling',
   'S3E19 Rise',
   'S3E20 Favorite Son',
   'S3E21 Before and After',
   'S3E22 Real Life',
   'S3E23 Distant Origin',
   'S3E24 Displaced',
   'S3E25 Worst Case Scenario',
   'S3E26 Scorpion, Part I',
   'S4E01 Scorpion: Part II',
   'S4E02 The Gift',
   'S4E03 Day of Honor',
   'S4E04 Nemesis',
   'S4E05 Revulsion',
   'S4E06 The Raven',
   'S4E07 Scientific Method',
   'S4E08 Year of Hell: Part I',
   'S4E09 Year of Hell: Part II',
   'S4E10 Random Thoughts',
   'S4E11 Concerning Flight',
   'S4E12 Mortal Coil',
   'S4E13 Waking Moments',
   'S4E14 Message in a Bottle',
   'S4E15 Hunters',
   'S4E16 Prey',
   'S4E17 Retrospect',
   'S4E18 The Killing Game Part I',
   'S4E19 The Killing Game Part II',
   'S4E20 Vis à Vis',
   'S4E21 The Omega Directive',
   'S4E22 Unforgettable',
   'S4E23 Living Witness',
   'S4E24 Demon',
   'S4E25 One',
   'S4E26 Hope and Fear',
   'S5E01 Night',
   'S5E02 Drone',
   'S5E03 Extreme Risk',
   'S5E04 In the Flesh',
   'S5E05 Once Upon a Time',
   'S5E06 Timeless',
   'S5E07 Infinite Regress',
   'S5E08 Nothing Human',
   'S5E09 Thirty Days',
   'S5E10 Counterpoint',
   'S5E11 Latent Image',
   'S5E12 Bride of Chaotica!',
   'S5E13 Gravity',
   'S5E14 Bliss',
   'S5E15 Dark Frontier Part I',
   'S5E16 Dark Frontier Part II',
   'S5E17 The Disease',
   'S5E18 Course: Oblivion',
   'S5E19 The Fight',
   'S5E20 Think Tank',
   'S5E21 Juggernaut',
   'S5E22 Someone to Watch Over Me',
   'S5E23 11:59',
   'S5E24 Relativity',
   'S5E25 Warhead',
   'S5E26 Equinox, Part I',
   'S6E01 Equinox: Part II',
   'S6E02 Survival Instinct',
   'S6E03 Barge of the Dead',
   'S6E04 Tinker, Tenor, Doctor, Spy',
   'S6E05 Alice',
   'S6E06 Riddles',
   'S6E07 Dragons Teeth',
   'S6E08 One Small Step',
   'S6E09 The Voyager Conspiracy',
   'S6E10 Pathfinder',
   'S6E11 Fair Haven',
   'S6E12 Blink of an Eye',
   'S6E13 Virtuoso',
   'S6E14 Memorial',
   'S6E15 Tsunkatse',
   'S6E16 Collective',
   'S6E17 Spirit Folk',
   'S6E18 Ashes to Ashes',
   'S6E19 Childs Play',
   'S6E20 Good Shepherd',
   'S6E21 Live Fast and Prosper',
   'S6E22 Muse',
   'S6E23 Fury',
   'S6E24 Life Line',
   'S6E25 The Haunting of Deck Twelve',
   'S6E26 Unimatrix Zero: Part I',
   'S7E01 Unimatrix Zero, Part II',
   'S7E02 Imperfection',
   'S7E03 Drive',
   'S7E04 Repression',
   'S7E05 Critical Care',
   'S7E06 Inside Man',
   'S7E07 Body and Soul',
   'S7E08 Nightingale',
   'S7E09 Flesh and Blood Part I',
   'S7E10 Flesh and Blood Part II',
   'S7E11 Shattered',
   'S7E12 Lineage',
   'S7E13 Repentance',
   'S7E14 Prophecy',
   'S7E15 The Void',
   'S7E16 Workforce, Part I',
   'S7E17 Workforce, Part II',
   'S7E18 Human Error',
   'S7E19 Q2',
   'S7E20 Author, Author',
   'S7E21 Friendship One',
   'S7E22 Natural Law',
   'S7E23 Homestead',
   'S7E24 Renaissance Man',
   'S7E25 Endgame Part I',
   'S7E26 Endgame Part II',
]

Eepisodes = [
   'S1E01 Broken Bow Part I',
   'S1E02 Broken Bow Part II',
   'S1E03 Fight or Flight',
   'S1E04 Strange New World',
   'S1E05 Unexpected',
   'S1E06 Terra Nova',
   'S1E07 The Andorian Incident',
   'S1E08 Breaking the Ice',
   'S1E09 Civilization',
   'S1E10 Fortunate Son',
   'S1E11 Cold Front',
   'S1E12 Silent Enemy',
   'S1E13 Dear Doctor',
   'S1E14 Sleeping Dogs',
   'S1E15 Shadows of PJem',
   'S1E16 Shuttlepod One',
   'S1E17 Fusion',
   'S1E18 Rogue Planet',
   'S1E19 Acquisition',
   'S1E20 Oasis',
   'S1E21 Detained',
   'S1E22 Vox Sola',
   'S1E23 Fallen Hero',
   'S1E24 Desert Crossing',
   'S1E25 Two Days and Two Nights',
   'S1E26 Shockwave, Part I',
   'S2E01 Shockwave: Part 2',
   'S2E02 Carbon Creek',
   'S2E03 Minefield',
   'S2E04 Dead Stop',
   'S2E05 A Night In Sickbay',
   'S2E06 Marauders',
   'S2E07 The Seventh',
   'S2E08 The Communicator',
   'S2E09 Singularity',
   'S2E10 Vanishing Point',
   'S2E11 Precious Cargo',
   'S2E12 The Catwalk',
   'S2E13 Dawn',
   'S2E14 Stigma',
   'S2E15 Cease Fire',
   'S2E16 Future Tense',
   'S2E17 Canamar',
   'S2E18 The Crossing',
   'S2E19 Judgment',
   'S2E20 Horizon',
   'S2E21 The Breach',
   'S2E22 Cogenitor',
   'S2E23 Regeneration',
   'S2E24 First Flight',
   'S2E25 Bounty',
   'S2E26 The Expanse',
   'S3E01 The Xindi',
   'S3E02 Anomaly',
   'S3E03 Extinction',
   'S3E04 Rajiin',
   'S3E05 Impulse',
   'S3E06 Exile',
   'S3E07 The Shipment',
   'S3E08 Twilight',
   'S3E09 North Star',
   'S3E10 Similitude',
   'S3E11 Carpenter Street',
   'S3E12 Chosen Realm',
   'S3E13 Proving Ground',
   'S3E14 Stratagem',
   'S3E15 Harbinger',
   'S3E16 Doctors Orders',
   'S3E17 Hatchery',
   'S3E18 Azati Prime',
   'S3E19 Damage',
   'S3E20 The Forgotten',
   'S3E21 E²',
   'S3E22 The Council',
   'S3E23 Countdown',
   'S3E24 Zero Hour',
   'S4E01 Storm Front',
   'S4E02 Storm Front, Part II',
   'S4E03 Home',
   'S4E04 Borderland',
   'S4E05 Cold Station 12',
   'S4E06 The Augments',
   'S4E07 The Forge',
   'S4E08 Awakening',
   'S4E09 KirShara',
   'S4E10 Daedalus',
   'S4E11 Observer Effect',
   'S4E12 Babel One',
   'S4E13 United',
   'S4E14 The Aenar',
   'S4E15 Affliction',
   'S4E16 Divergence',
   'S4E17 Bound',
   'S4E18 In a Mirror, Darkly',
   'S4E19 In a Mirror, Darkly, Part II',
   'S4E20 Demons',
   'S4E21 Terra Prime',
   'S4E22 These Are the Voyages...',
]

TASepisodes = [
   'S1E01 Beyond the Farthest Star',
   'S1E02 Yesteryear',
   'S1E03 One of Our Planets Is Missing',
   'S1E04 The Lorelei Signal',
   'S1E05 More Tribbles, More Troubles',
   'S1E06 The Survivor',
   'S1E07 The Infinite Vulcan',
   'S1E08 The Magicks of Megas-tu',
   'S1E09 Once Upon a Planet',
   'S1E10 Mudds Passion',
   'S1E11 The Terratin Incident',
   'S1E12 The Time Trap',
   'S1E13 The Ambergris Element',
   'S1E14 The Slaver Weapon',
   'S1E15 The Eye of the Beholder',
   'S1E16 The Jihad',
   'S2E01 The Pirates of Orion',
   'S2E02 Bem',
   'S2E03 The Practical Joker',
   'S2E04 Albatross',
   'S2E05 How Sharper Than a Serpents Tooth',
   'S2E06 The Counter-Clock Incident',
]

Depisodes = [
   'S1E01 The Vulcan Hello',
   'S1E02 Battle at the Binary Stars',
   'S1E03 Context Is for Kings',
   'S1E04 The Butchers Knife Cares Not for the Lambs Cry',
   'S1E05 Choose Your Pain',
   'S1E06 Lethe',
   'S1E07 Magic to Make the Sanest Man Go Mad',
   'S1E08 Si Vis Pacem, Para Bellum',
   'S1E09 Into the Forest I Go',
   'S1E10 Despite Yourself',
   'S1E11 The Wolf Inside',
   'S1E12 Vaulting Ambition',
   'S1E13 Whats Past Is Prologue',
   'S1E14 The War Without, The War Within',
   'S1E15 Will You Take My Hand?',
   'S2E01 Brother',
   'S2E02 New Eden',
   'S2E03 Point of Light',
   'S2E04 An Obol for Charon',
   'S2E05 Saints of Imperfection',
   'S2E06 The Sound of Thunder',
   'S2E07 Light and Shadows',
   'S2E08 If Memory Serves',
   'S2E09 Project Daedalus',
   'S2E10 The Red Angel',
   'S2E11 Perpetual Infinity',
   'S2E12 Through the Valley of Shadows',
   'S2E13 Such Sweet Sorrow Part I',
   'S2E14 Such Sweet Sorrow Part II',
   'S3E01 That Hope Is You, Part 1',
   'S3E02 Far from Home',
   'S3E03 People of Earth',
   'S3E04 Forget Me Not',
   'S3E05 Die Trying',
   'S3E06 Scavengers',
   'S3E07 Unification III',
   'S3E08 The Sanctuary',
   'S3E09 Terra Firma Part I',
   'S3E10 Terra Firma Part II',
   'S3E11 SuKal',
   'S3E12 There Is a Tide...',
   'S3E13 That Hope Is You, Part 2',
   'S4E01 Kobayashi Maru',
   'S4E02 Anomaly',
   'S4E03 Choose to Live',
   'S4E04 All Is Possible',
   'S4E05 The Examples',
   'S4E06 Stormy Weather',
   'S4E07 ...But to Connect',
   'S4E08 All In',
   'S4E09 Rubicon',
   'S4E10 The Galactic Barrier',
   'S4E11 Rosetta',
   'S4E12 Species Ten-C',
   'S4E13 Coming Home',
]

STepisodes = [
   'S1E01 Runaway',
   'S1E02 Calypso',
   'S1E03 The Brightest Star',
   'S1E04 The Escape Artist',
   'S2E01 Q&A',
   'S2E02 The Trouble with Edward',
   'S2E03 Ask Not',
   'S2E04 Ephraim and Dot',
   'S2E05 The Girl Who Made the Stars',
   'S2E06 Children of Mars',
]

Pepisodes = [
   'S1E01 Remembrance',
   'S1E02 Maps and Legends',
   'S1E03 The End Is the Beginning',
   'S1E04 Absolute Candor',
   'S1E05 Stardust City Rag',
   'S1E06 The Impossible Box',
   'S1E07 Nepenthe',
   'S1E08 Broken Pieces',
   'S1E09 Et in Arcadia Ego Part I',
   'S1E10 Et in Arcadia Ego Part II',
   'S2E01 The Star Gazer',
   'S2E02 Penance',
   'S2E03 Assimilation',
   'S2E04 Watcher',
   'S2E05 Fly Me to the Moon',
   'S2E06 Two of One',
   'S2E07 Monsters',
   'S2E08 Mercy',
   'S2E09 Hide and Seek',
   'S2E10 Farewell',
]

LDepisodes = [
   'S1E01 Second Contact',
   'S1E02 Envoys',
   'S1E03 Temporal Edict',
   'S1E04 Moist Vessel',
   'S1E05 Cupids Errant Arrow',
   'S1E06 Terminal Provocations',
   'S1E07 Much Ado About Boimler',
   'S1E08 Veritas',
   'S1E09 Crisis Point',
   'S1E10 No Small Parts',
   'S2E01 Strange Energies',
   'S2E02 Kayshon, His Eyes Open',
   'S2E03 Well Always Have Tom Paris',
   'S2E04 Mugato, Gumato',
   'S2E05 An Embarrassment of Dooplers',
   'S2E06 The Spy Humongous',
   'S2E07 Where Pleasant Fountains Lie',
   'S2E08 I, Excretus',
   'S2E09 wej Duj',
   'S2E10 First First Contact',
   'S3E01 Grounded',
   'S3E02 The Least Dangerous Game',
   'S3E03 Mining the Minds Mines',
   'S3E04 Room for Growth',
   'S3E05 Reflections',
   'S3E06 Hear All, Trust Nothing',
   'S3E07 A Mathematically Perfect Redemption',
   'S3E08 Crisis Point 2: Paradoxus',
   'S3E09 Trusted Sources',
   'S3E10 The Stars at Night',
]

Pepisodes1 = [
   'S1E01 Lost and Found Part I',
   'S1E02 Lost and Found Part II',
   'S1E03 Starstruck',
   'S1E04 Dream Catcher',
   'S1E05 Terror Firma',
   'S1E06 Kobayashi',
   'S1E07 First Con-tact',
   'S1E08 Time Amok',
   'S1E09 A Moral Star Part I',
   'S1E10 A Moral Star Part II',
   'S1E11 Asylum',
   'S1E12 Let Sleeping Borg Lie',
]

SNWepisodes = [
   'S1E01 Strange New Worlds',
   'S1E02 Children of the Comet',
   'S1E03 Ghosts of Illyria',
   'S1E04 Memento Mori',
   'S1E05 Spock Amok',
   'S1E06 Lift Us Where Suffering Cannot Reach',
   'S1E07 The Serene Squall',
   'S1E08 The Elysian Kingdom',
   'S1E09 All Those Who Wander',
   'S1E10 A Quality of Mercy',
]

# Movies

TNGmovies = [
   'Star Trek Generations (1994)',
   'Star Trek: First Contact (1996)',
   'Star Trek: Insurrection (1998)',
   'Star Trek: Nemesis (2002)',
]

TOSmovies = [
   'Star Trek: The Motion Picture (1979)',
   'Star Trek II: The Wrath of Khan (1982)',
   'Star Trek III: The Search for Spock (1984)',
   'Star Trek IV: The Voyage Home (1986)',
   'Star Trek V: The Final Frontier (1989)',
   'Star Trek VI: The Undiscovered Country (1991)',
]

RKmovies = [
   'Star Trek (2009)',
   'Star Trek Into Darkness (2013)',
   'Star Trek Beyond (2016)',
]

# Television Series labels

series = [
   'The Original Series',
   'The Animated Series',
   'The Next Generation',
   'Deep Space Nine',
   'Voyager',
   'Enterprise',
   'Discovery',
   'Short Treks',
   'Picard',
   'Lower Decks',
   'Prodigy',
   'Strange New Worlds',
]

# Movie Era labels

movieSeries = [
   'The Original Series films',
   'The Next Generation films',
   'Reboot (Kelvin timeline) films',
]

# Mappings

TVMapping = {
	0 : TOSepisodes,
	1 : TASepisodes,
	2 : TNGepisodes,
	3 : DSNepisodes,
	4 : Vepisodes,
	5 : Eepisodes,
	6 : Depisodes,
	7 : STepisodes,
	8 : Pepisodes,
	9 : LDepisodes,
	10 : Pepisodes1,
	11 : SNWepisodes,
}

MovieMapping = {
	0 : TOSmovies,
	1 : TNGmovies,
	2 : RKmovies,
}

while(True):
    print("\n"+
          "\t               .\n"+
          "\t              .:.\n"+
          "\t             .:::.\n"+
          "\t            .:::::.\n"+
          "\t        ***.:::::::.***\n"+
          "\t   *******.:::::::::.*******\n"+
          "\t ********.:::::::::::.********\n"+
          "\t********.:::::::::::::.********\n"+
          "\t*******.::::::\'***`::::.*******\n"+
          "\t******.::::\'*********`::.******\n"+
          "\t ****.:::\'*************`:.****\n"+
          "\t   *.::\'*****************`.*\n"+
          "\t   .:\'  ***************    .\n"+
          "\t  .\n"+
          "\t\n"+
          "\t\n"+
          "\tRandom Star Trek Media Picker")
    
    typeMedia = ''
    while(len(typeMedia) == 0):
        typeMedia = input('\n( 1 ) TV\n( 2 ) Movies\n( 3 ) I\'m Feeling Lucky\n( 4 ) Quit\n\nWhat kind of Media? : ')

    typeMedia = int(typeMedia)
    
    if(typeMedia == 4):
      exit()

    show = ''

    if(typeMedia == 3):
      show = '-1'

    while(len(show) == 0):
        count = 0
        print('')
        if(typeMedia == 1):
          for showtype in series:
              print('(',count,') ',showtype)
              count+=1
        else:
          for showtype in movieSeries:
              print('(',count,') ',showtype)
              count+=1

        show = input('\nWhich show? : ')

    show = int(show)
    repeat = ''
    while(len(str(repeat)) == 0 or repeat == 1 or repeat == 3):
        result = ''
        if(repeat != 3):
          if(typeMedia == 1):
              targetArr = TVMapping.get(show)
              result = targetArr[random.randint(0,len(targetArr)-1)]
              print('\n  ',series[show])
              print('\n\t',result)
          elif(typeMedia == 3):
              mappingIndex = random.randint(0,1)
              targetMapping = TVMapping if mappingIndex == 0 else MovieMapping
              selectedMapping = random.randint(0,len(targetMapping)-1)
              targetShow = targetMapping[selectedMapping]
              result = targetShow[random.randint(0,len(targetShow)-1)]
              print('\n  ',(series if mappingIndex == 0 else movieSeries)[selectedMapping])
              print('\n\t',result)
          else:
              targetArr = MovieMapping.get(show)
              result = targetArr[random.randint(0,len(targetArr)-1)]
              print('\n  ',movieSeries[show])
              print('\n\t',result)
  
        repeat = input('\n( 1 ) Yes\n( 2 ) No\n( 3 ) Open in Browser\n( 4 ) Open in Browser and Close\n\nRepeat? : ')
        repeat = int(repeat)

        if(repeat == 3 or repeat == 4):
          webbrowser.open_new_tab('https://www.google.com/search?q='+result.replace(' ','+'))
          if(repeat == 4):
            exit()
