import random
import time
import webbrowser

random.seed(time.time())

series = [
   'Star Trek The Original Series',
   'Star Trek The Animated Series',
   'Star Trek The Next Generation',
   'Star Trek Deep Space Nine',
   'Star Trek Voyager',
   'Star Trek Enterprise',
   'Star Trek Discovery',
   'Star Trek Picard',
   'Star Trek Lower Decks'
]

movieSeries = [
   'Star Trek The Original Series',
   'Star Trek The Next Generation',
   'Star Trek Reboot Movies',
]

TOSepisode = [
   'S1E01 The Man Trap',
   'S1E02 Charlie X',
   'S1E03 Where No Man Has Gone Before',
   'S1E04 The Naked Time',
   'S1E05 The Enemy Within',
   'S1E06 Mudds Women',
   'S1E07 What Are Little Girls Made Of?',
   'S1E08 Miri',
   'S1E09 Dagger of the Mind',
   'S1E10 The Corbomite Maneuver',
   'S1E11 The Menagerie, Part I',
   'S1E12 The Menagerie, Part II',
   'S1E13 The Conscience of the King',
   'S1E14 Balance of Terror',
   'S1E15 Shore Leave',
   'S1E16 The Galileo Seven',
   'S1E17 The Squire of Gothos',
   'S1E18 Arena',
   'S1E19 Tomorrow Is Yesterday',
   'S1E20 Court Martial',
   'S1E21 The Return of the Archons',
   'S1E22 Space Seed',
   'S1E23 A Taste of Armageddon',
   'S1E24 This Side of Paradise',
   'S1E25 The Devil in the Dark',
   'S1E26 Errand of Mercy',
   'S1E27 The Alternative Factor',
   'S1E28 The City on the Edge of Forever',
   'S1E29 Operation: Annihilate!',
   'S2E01 Amok Time',
   'S2E02 Who Mourns for Adonais?',
   'S2E03 The Changeling',
   'S2E04 Mirror, Mirror',
   'S2E05 The Apple',
   'S2E06 The Doomsday Machine',
   'S2E07 Catspaw',
   'S2E08 I, Mudd',
   'S2E09 Metamorphosis',
   'S2E10 Journey to Babel',
   'S2E11 Fridays Child',
   'S2E12 The Deadly Years',
   'S2E13 Obsession',
   'S2E14 Wolf in the Fold',
   'S2E15 The Trouble With Tribbles',
   'S2E16 The Gamesters of Triskelion',
   'S2E17 A Piece of the Action',
   'S2E18 The Immunity Syndrome',
   'S2E19 A Private Little War',
   'S2E20 Return to Tomorrow',
   'S2E21 Patterns of Force',
   'S2E22 By Any Other Name',
   'S2E23 The Omega Glory',
   'S2E24 The Ultimate Computer',
   'S2E25 Bread and Circuses',
   'S2E26 Assignment: Earth',
   'S3E01 Spocks Brain',
   'S3E02 The Enterprise Incident',
   'S3E03 The Paradise Syndrome',
   'S3E04 And the Children Shall Lead',
   'S3E05 Is There in Truth No Beauty?',
   'S3E06 Spectre of the Gun',
   'S3E07 Day of the Dove',
   'S3E08 For the World Is Hollow and I Have Touched the Sky',
   'S3E09 The Tholian Web',
   'S3E10 Platos Stepchildren',
   'S3E11 Wink of an Eye',
   'S3E12 The Empath',
   'S3E13 Elaan of Troyius',
   'S3E14 Whom Gods Destroy',
   'S3E15 Let That Be Your Last Battlefield',
   'S3E16 The Mark of Gideon',
   'S3E17 That Which Survives',
   'S3E18 The Lights of Zetar',
   'S3E19 Requiem for Methuselah',
   'S3E20 The Way to Eden',
   'S3E21 The Cloud Minders',
   'S3E22 The Savage Curtain',
   'S3E23 All Our Yesterdays',
   'S3E24 Turnabout Intruder',
]

TNGepisode = [
  'S1E1-2 Encounter at Farpoint',
  'S1E3 The Naked Now',
  'S1E4 Code of Honor',
  'S1E5 The Last Outpost',
  'S1E6 Where No One Has Gone Before',
  'S1E7 Lonely Among Us',
  'S1E8 Justice',
  'S1E9 The Battle',
  'S1E10 Hide and Q',
  'S1E11 Haven',
  'S1E12 The Big Goodbye',
  'S1E13 Datalore',
  'S1E14 Angel One',
  'S1E15 11001001',
  'S1E16 Too Short a Season',
  'S1E17 When the Bough Breaks',
  'S1E18 Home Soil',
  'S1E19 Coming of Age',
  'S1E20 Heart of Glory',
  'S1E21 The Arsenal of Freedom',
  'S1E22 Symbiosis',
  'S1E23 Skin of Evil',
  'S1E24 Well Always Have Paris',
  'S1E25 Conspiracy',
  'S1E26 The Neutral Zone',
  'S2E1 The Child',
  'S2E2 Where Silence Has Lease',
  'S2E3 Elementary, Dear Data',
  'S2E4 The Outrageous Okona',
  'S2E5 Loud as a Whisper',
  'S2E6 The Schizoid Man',
  'S2E7 Unnatural Selection',
  'S2E8 A Matter of Honor',
  'S2E9 The Measure of a Man',
  'S2E10 The Dauphin',
  'S2E11 Contagion',
  'S2E12 The Royale',
  'S2E13 Time Squared',
  'S2E14 The Icarus Factor',
  'S2E15 Pen Pals',
  'S2E16 Q Who',
  'S2E17 Samaritan Snare',
  'S2E18 Up the Long Ladder',
  'S2E19 Manhunt',
  'S2E20 The Emissary',
  'S2E21 Peak Performance',
  'S2E22 Shades of Gray (might want to pick again)',
  'S3E1 Evolution',
  'S3E2 The Ensigns of Command',
  'S3E3 The Survivors',
  'S3E4 Who Watches the Watchers',
  'S3E5 The Bonding',
  'S3E6 Booby Trap',
  'S3E7 The Enemy',
  'S3E8 The Price',
  'S3E9 The Vengeance Factor',
  'S3E10 The Defector',
  'S3E11 The Hunted',
  'S3E12 The High Ground',
  'S3E13 Deja Q',
  'S3E14 A Matter of Perspective',
  'S3E15 Yesterdays Enterprise',
  'S3E16 The Offspring',
  'S3E17 Sins of the Father',
  'S3E18 Allegiance',
  'S3E19 Captains Holiday',
  'S3E20 Tin Man',
  'S3E21 Hollow Pursuits',
  'S3E22 The Most Toys',
  'S3E23 Sarek',
  'S3E24 Menage a Troi',
  'S3E25 Transfigurations',
  'S3E26 The Best of Both Worlds: Part One',
  'S4E1 The Best of Both Worlds: Part Two',
  'S4E2 Family',
  'S4E3 Brothers',
  'S4E4 Suddenly Human',
  'S4E5 Remember Me',
  'S4E6 Legacy',
  'S4E7 Reunion',
  'S4E8 Future Imperfect',
  'S4E9 Final Mission',
  'S4E10 The Loss',
  'S4E11 Datas Day',
  'S4E12 The Wounded',
  'S4E13 Devils Due',
  'S4E14 Clues',
  'S4E15 First Contact',
  'S4E16 Galaxys Child',
  'S4E17 Night Terrors',
  'S4E18 Identity Crisis',
  'S4E19 The Nth Degree',
  'S4E20 Qpid',
  'S4E21 The Drumhead',
  'S4E22 Half a Life',
  'S4E23 The Host',
  'S4E24 The Minds Eye',
  'S4E25 In Theory',
  'S4E26 Redemption: Part One',
  'S5E1 Redemption: Part Two',
  'S5E2 Darmok',
  'S5E3 Ensign Ro',
  'S5E4 Silicon Avatar',
  'S5E5 Disaster',
  'S5E6 The Game',
  'S5E7 Unification: Part One',
  'S5E8 Unification: Part Two',
  'S5E9 A Matter of Time',
  'S5E10 New Ground',
  'S5E11 Hero Worship',
  'S5E12 Violations',
  'S5E13 The Masterpiece Society',
  'S5E14 Conundrum',
  'S5E15 Power Play',
  'S5E16 Ethics',
  'S5E17 The Outcast',
  'S5E18 Cause and Effect',
  'S5E19 The First Duty',
  'S5E20 Cost of Living',
  'S5E21 The Perfect Mate',
  'S5E22 Imaginary Friend',
  'S5E23 I Borg',
  'S5E24 The Next Phase',
  'S5E25 The Inner Light',
  'S5E26 Times Arrow: Part One',
  'S6E1 Times Arrow: Part Two',
  'S6E2 Realm of Fear',
  'S6E3 Man of the People',
  'S6E4 Relics',
  'S6E5 Schisms',
  'S6E6 True Q',
  'S6E7 Rascals',
  'S6E8 A Fistful of Datas',
  'S6E9 The Quality of Life',
  'S6E10 Chain of Command: Part One',
  'S6E11 Chain of Command: Part Two',
  'S6E12 Ship in a Bottle',
  'S6E13 Aquiel',
  'S6E14 Face of the Enemy',
  'S6E15 Tapestry',
  'S6E16 Birthright: Part One',
  'S6E17 Birthright: Part Two',
  'S6E18 Starship Mine',
  'S6E19 Lessons',
  'S6E20 The Chase',
  'S6E21 Frame of Mind',
  'S6E22 Suspicions',
  'S6E23 Rightful Heir',
  'S6E24 Second Chances',
  'S6E25 Timescape',
  'S6E26 Descent: Part One',
  'S7E1 Descent: Part Two',
  'S7E2 Liaisons',
  'S7E3 Interface',
  'S7E4 Gambit: Part One',
  'S7E5 Gambit: Part Two',
  'S7E6 Phantasms',
  'S7E7 Dark Page',
  'S7E8 Attached',
  'S7E9 Force of Nature',
  'S7E10 Inheritance',
  'S7E11 Parallels',
  'S7E12 The Pegasus',
  'S7E13 Homeward',
  'S7E14 Sub Rosa',
  'S7E15 Lower Decks',
  'S7E16 Thine Own Self',
  'S7E17 Masks',
  'S7E18 Eye of the Beholder',
  'S7E19 Genesis',
  'S7E20 Journeys End',
  'S7E21 Firstborn',
  'S7E22 Bloodlines',
  'S7E23 Emergence',
  'S7E24 Preemptive Strike',
  'S7E25 All Good Things...'
]

DS9episode = [
  'S1E1 Emissary, Part I',
  'S1E2 Emissary, Part II',
  'S1E3 Past Prologue',
  'S1E4 A Man Alone',
  'S1E5 Babel',
  'S1E6 Captive Pursuit',
  'S1E7 Q-Less',
  'S1E8 Dax',
  'S1E9 The Passenger',
  'S1E10 Move Along Home',
  'S1E11 The Nagus',
  'S1E12 Vortex',
  'S1E13 Battle Lines',
  'S1E14 The Storyteller',
  'S1E15 Progress',
  'S1E16 If Wishes Were Horses',
  'S1E17 The Forsaken',
  'S1E18 Dramatis Personae',
  'S1E19 Duet',
  'S1E20 In the Hands of the Prophets',
  'S2E1 The Homecoming (Part 1)',
  'S2E2 The Circle (Part 2)',
  'S2E3 The Siege (Part 3)',
  'S2E4 Invasive Procedures',
  'S2E5 Cardassians',
  'S2E6 Melora',
  'S2E7 Rules of Acquisition',
  'S2E8 Necessary Evil',
  'S2E9 Second Sight',
  'S2E10 Sanctuary',
  'S2E11 Rivals',
  'S2E12 The Alternate',
  'S2E13 Armageddon Game',
  'S2E14 Whispers',
  'S2E15 Paradise',
  'S2E16 Shadowplay',
  'S2E17 Playing God',
  'S2E18 Profit and Loss',
  'S2E19 Blood Oath',
  'S2E20 The Maquis, Part I',
  'S2E21 The Maquis, Part II',
  'S2E22 The Wire',
  'S2E23 Crossover',
  'S2E24 The Collaborator',
  'S2E25 Tribunal',
  'S2E26 The JemHadar',
  'S3E1 The Search, Part I',
  'S3E2 The Search, Part II',
  'S3E3 The House of Quark',
  'S3E4 Equilibrium',
  'S3E5 Second Skin',
  'S3E6 The Abandoned',
  'S3E7 Civil Defense',
  'S3E8 Meridian',
  'S3E9 Defiant',
  'S3E10 Fascination',
  'S3E11 Past Tense, Part I',
  'S3E12 Past Tense, Part II',
  'S3E13 Life Support',
  'S3E14 Heart of Stone',
  'S3E15 Destiny',
  'S3E16 Prophet Motive',
  'S3E17 Visionary',
  'S3E18 Distant Voices',
  'S3E19 Through the Looking Glass',
  'S3E20 Improbable Cause (Part 1)',
  'S3E21 The Die is Cast (Part 2)',
  'S3E22 Explorers',
  'S3E23 Family Business',
  'S3E24 Shakaar',
  'S3E25 Facets',
  'S3E26 The Adversary',
  'S4E1 The Way of the Warrior, Part I',
  'S4E2 The Way of the Warrior, Part II',
  'S4E3 The Visitor',
  'S4E4 Hippocratic Oath',
  'S4E5 Indiscretion',
  'S4E6 Rejoined',
  'S4E7 Starship Down',
  'S4E8 Little Green Men',
  'S4E9 The Sword of Kahless',
  'S4E10 Our Man Bashir',
  'S4E11 Homefront (Part 1)',
  'S4E12 Paradise Lost (Part 2)',
  'S4E13 Crossfire',
  'S4E14 Return to Grace',
  'S4E15 Sons of Mogh',
  'S4E16 Bar Association',
  'S4E17 Accession',
  'S4E18 Rules of Engagement',
  'S4E19 Hard Time',
  'S4E20 Shattered Mirror',
  'S4E21 The Muse',
  'S4E22 For the Cause',
  'S4E23 To the Death',
  'S4E24 The Quickening',
  'S4E25 Body Parts',
  'S4E26 Broken Link',
  'S5E1 Apocalypse Rising',
  'S5E2 The Ship',
  'S5E3 Looking for parMach in All the Wrong Places',
  'S5E4 ...Nor the Battle to the Strong',
  'S5E5 The Assignment',
  'S5E6 Trials and Tribble-ations',
  'S5E7 Let He Who Is Without Sin...',
  'S5E8 Things Past',
  'S5E9 The Ascent',
  'S5E10 Rapture',
  'S5E11 The Darkness and the Light',
  'S5E12 The Begotten',
  'S5E13 For the Uniform',
  'S5E14 In Purgatorys Shadow (Part 1)',
  'S5E15 By Infernos Light (Part 2)',
  'S5E16 Doctor Bashir, I Presume?',
  'S5E17 A Simple Investigation',
  'S5E18 Business as Usual',
  'S5E19 Ties of Blood and Water',
  'S5E20 Ferengi Love Songs',
  'S5E21 Soldiers of the Empire',
  'S5E22 Children of Time',
  'S5E23 Blaze of Glory',
  'S5E24 Empok Nor',
  'S5E25 In the Cards',
  'S5E26 Call to Arms',
  'S6E1 A Time to Stand',
  'S6E2 Rocks and Shoals',
  'S6E3 Sons and Daughters',
  'S6E4 Behind the Lines',
  'S6E5 Favor the Bold (Part 1)',
  'S6E6 Sacrifice of Angels (Part 2)',
  'S6E7 You are Cordially Invited...',
  'S6E8 Resurrection',
  'S6E9 Statistical Probabilities',
  'S6E10 The Magnificent Ferengi',
  'S6E11 Waltz',
  'S6E12 Who Mourns for Morn?',
  'S6E13 Far Beyond the Stars',
  'S6E14 One Little Ship',
  'S6E15 Honor Among Thieves',
  'S6E16 Change of Heart',
  'S6E17 Wrongs Darker Than Death or Night',
  'S6E18 Inquisition',
  'S6E19 In the Pale Moonlight',
  'S6E20 His Way',
  'S6E21 The Reckoning',
  'S6E22 Valiant',
  'S6E23 Profit and Lace',
  'S6E24 Times Orphan',
  'S6E25 The Sound of Her Voice',
  'S6E26 Tears of the Prophets',
  'S7E1 Image in the Sand',
  'S7E2 Shadows and Symbols',
  'S7E3 Afterimage',
  'S7E4 Take Me Out to the Holosuite',
  'S7E5 Chrysalis',
  'S7E6 Treachery, Faith, and the Great River',
  'S7E7 Once More Unto the Breach',
  'S7E8 The Siege of AR-558',
  'S7E9 Covenant',
  'S7E10 Its Only a Paper Moon',
  'S7E11 Prodigal Daughter',
  'S7E12 The Emperors New Cloak',
  'S7E13 Field of Fire',
  'S7E14 Chimera',
  'S7E15 Badda-Bing Badda-Bang',
  'S7E16 Inter Arma Enim Silent Leges',
  'S7E17 Penumbra',
  'S7E18 Til Death Do Us Part',
  'S7E19 Strange Bedfellows',
  'S7E20 The Changing Face of Evil',
  'S7E21 When It Rains...',
  'S7E22 Tacking Into the Wind',
  'S7E23 Extreme Measures',
  'S7E24 The Dogs of War',
  'S7E25 What You Leave Behind'
]

VOYepisode = [
  'S1E1-2 Caretaker',
  'S1E3 Parallax',
  'S1E4 Time and Again',
  'S1E5 Phage',
  'S1E6 The Cloud',
  'S1E7 Eye of the Needle',
  'S1E8 Ex Post Facto',
  'S1E9 Emanations',
  'S1E10 Prime Factors',
  'S1E11 State of Flux',
  'S1E12 Heroes and Demons',
  'S1E13 Cathexis',
  'S1E14 Faces',
  'S1E15 Jetrel',
  'S1E16 Learning Curve',
  'S2E1 The 37s',
  'S2E2 Initiations',
  'S2E3 Projections',
  'S2E4 Elogium',
  'S2E5 Non Sequitur',
  'S2E6 Twisted',
  'S2E7 Parturition',
  'S2E8 Persistence of Vision',
  'S2E9 Tattoo',
  'S2E10 Cold Fire',
  'S2E11 Maneuvers',
  'S2E12 Resistance',
  'S2E13 Prototype',
  'S2E14 Alliances',
  'S2E15 Threshold',
  'S2E16 Meld',
  'S2E17 Dreadnought',
  'S2E18 Death Wish',
  'S2E19 Lifesigns',
  'S2E20 Investigations',
  'S2E21 Deadlock',
  'S2E22 Innocence',
  'S2E23 The Thaw',
  'S2E24 Tuvix',
  'S2E25 Resolutions',
  'S2E26 Basics, Part I',
  'S3E1 Basics, Part II',
  'S3E2 Flashback',
  'S3E3 The Chute',
  'S3E4 The Swarm',
  'S3E5 False Profits',
  'S3E6 Remember',
  'S3E7 Sacred Ground',
  'S3E8 Futures End, Part I',
  'S3E9 Futures End, Part II',
  'S3E10 Warlord',
  'S3E11 The Q and the Grey',
  'S3E12 Macrocosm',
  'S3E13 Fair Trade',
  'S3E14 Alter Ego',
  'S3E15 Coda',
  'S3E16 Blood Fever',
  'S3E17 Unity',
  'S3E18 Darkling',
  'S3E19 Rise',
  'S3E20 Favorite Son',
  'S3E21 Before and After',
  'S3E22 Real Life',
  'S3E23 Distant Origin',
  'S3E24 Displaced',
  'S3E25 Worst Case Scenario',
  'S3E26 Scorpion, Part I',
  'S4E1 Scorpion, Part II',
  'S4E2 The Gift',
  'S4E3 Day of Honor',
  'S4E4 Nemesis',
  'S4E5 Revulsion',
  'S4E6 The Raven',
  'S4E7 Scientific Method',
  'S4E8 Year of Hell, Part I',
  'S4E9 Year of Hell, Part II',
  'S4E10 Random Thoughts',
  'S4E11 Concerning Flight',
  'S4E12 Mortal Coil',
  'S4E13 Waking Moments',
  'S4E14 Message in a Bottle',
  'S4E15 Hunters',
  'S4E16 Prey',
  'S4E17 Retrospect',
  'S4E18 The Killing Game, Part I',
  'S4E19 The Killing Game, Part II',
  'S4E20 Vis À Vis',
  'S4E21 The Omega Directive',
  'S4E22 Unforgettable',
  'S4E23 Living Witness',
  'S4E24 Demon',
  'S4E25 One',
  'S4E26 Hope and Fear',
  'S5E1 Night',
  'S5E2 Drone',
  'S5E3 Extreme Risk',
  'S5E4 In the Flesh',
  'S5E5 Once Upon a Time',
  'S5E6 Timeless',
  'S5E7 Infinite Regress',
  'S5E8 Nothing Human',
  'S5E9 Thirty Days',
  'S5E10 Counterpoint',
  'S5E11 Latent Image',
  'S5E12 Bride of Chaotica!',
  'S5E13 Gravity',
  'S5E14 Bliss',
  'S5E15 Dark Frontier, Part I',
  'S5E16 Dark Frontier, Part II',
  'S5E17 The Disease',
  'S5E18 Course: Oblivion',
  'S5E19 The Fight',
  'S5E20 Think Tank',
  'S5E21 Juggernaut',
  'S5E22 Someone to Watch Over Me',
  'S5E23 11:59',
  'S5E24 Relativity',
  'S5E25 Warhead',
  'S5E26 Equinox, Part I',
  'S6E1 Equinox, Part II',
  'S6E2 Survival Instinct',
  'S6E3 Barge of the Dead',
  'S6E4 Tinker, Tenor, Doctor, Spy',
  'S6E5 Alice',
  'S6E6 Riddles',
  'S6E7 Dragons Teeth',
  'S6E8 One Small Step',
  'S6E9 The Voyager Conspiracy',
  'S6E10 Pathfinder',
  'S6E11 Fair Haven',
  'S6E12 Blink of an Eye',
  'S6E13 Virtuoso',
  'S6E14 Memorial',
  'S6E15 Tsunkatse',
  'S6E16 Collective',
  'S6E17 Spirit Folk',
  'S6E18 Ashes to Ashes',
  'S6E19 Childs Play',
  'S6E20 Good Shepherd',
  'S6E21 Live Fast and Prosper',
  'S6E22 Muse',
  'S6E23 Fury',
  'S6E24 Life Line',
  'S6E25 The Haunting of Deck Twelve',
  'S6E26 Unimatrix Zero, Part I',
  'S7E1 Unimatrix Zero, Part II',
  'S7E2 Imperfection',
  'S7E3 Drive',
  'S7E4 Repression',
  'S7E5 Critical Care',
  'S7E6 Inside Man',
  'S7E7 Body and Soul',
  'S7E8 Nightingale',
  'S7E9 Flesh and Blood, Part II',
  'S7E10 Flesh and Blood, Part I',
  'S7E11 Shattered',
  'S7E12 Lineage',
  'S7E13 Repentance',
  'S7E14 Prophecy',
  'S7E15 The Void',
  'S7E16 Workforce, Part I',
  'S7E17 Workforce, Part II',
  'S7E18 Human Error',
  'S7E19 Q2',
  'S7E20 Author, Author',
  'S7E21 Friendship One',
  'S7E22 Natural Law',
  'S7E23 Homestead',
  'S7E24 Renaissance Man',
  'S7E25 Endgame'
]

ENTepisode = [
  'S1E1-2 Broken Bow',
  'S1E3 Fight or Flight',
  'S1E4 Strange New World',
  'S1E5 Unexpected',
  'S1E6 Terra Nova',
  'S1E7 The Andorian Incident',
  'S1E8 Breaking the Ice',
  'S1E9 Civilization',
  'S1E10 Fortunate Son',
  'S1E11 Cold Front',
  'S1E12 Silent Enemy',
  'S1E13 Dear Doctor',
  'S1E14 Sleeping Dogs',
  'S1E15 Shadows of PJem',
  'S1E16 Shuttlepod One',
  'S1E17 Fusion',
  'S1E18 Rogue Planet',
  'S1E19 Acquisition',
  'S1E20 Oasis',
  'S1E21 Detained',
  'S1E22 Vox Sola',
  'S1E23 Fallen Hero',
  'S1E24 Desert Crossing',
  'S1E25 Two Days and Two Nights',
  'S1E26 Shockwave, Part I',
  'S2E1 Shockwave, Part II',
  'S2E2 Carbon Creek',
  'S2E3 Minefield',
  'S2E4 Dead Stop',
  'S2E5 A Night In Sickbay',
  'S2E6 Marauders',
  'S2E7 The Seventh',
  'S2E8 The Communicator',
  'S2E9 Singularity',
  'S2E10 Vanishing Point',
  'S2E11 Precious Cargo',
  'S2E12 The Catwalk',
  'S2E13 Dawn',
  'S2E14 Stigma',
  'S2E15 Cease Fire',
  'S2E16 Future Tense',
  'S2E17 Canamar',
  'S2E18 The Crossing',
  'S2E19 Judgment',
  'S2E20 Horizon',
  'S2E21 The Breach',
  'S2E22 Cogenitor',
  'S2E23 Regeneration',
  'S2E24 First Flight',
  'S2E25 Bounty',
  'S2E26 The Expanse',
  'S3E1 The Xindi',
  'S3E2 Anomaly',
  'S3E3 Extinction',
  'S3E4 Rajiin',
  'S3E5 Impulse',
  'S3E6 Exile',
  'S3E7 The Shipment',
  'S3E8 Twilight',
  'S3E9 North Star',
  'S3E10 Similitude',
  'S3E11 Carpenter Street',
  'S3E12 Chosen Realm',
  'S3E13 Proving Ground',
  'S3E14 Stratagem',
  'S3E15 Harbinger',
  'S3E16 Doctors Orders',
  'S3E17 Hatchery',
  'S3E18 Azati Prime',
  'S3E19 Damage',
  'S3E20 The Forgotten',
  'S3E21 E²',
  'S3E22 The Council',
  'S3E23 Countdown',
  'S3E24 Zero Hour',
  'S4E1 Storm Front, Part I',
  'S4E2 Storm Front, Part II',
  'S4E3 Home',
  'S4E4 Borderland',
  'S4E5 Cold Station 12',
  'S4E6 The Augments',
  'S4E7 The Forge',
  'S4E8 Awakening',
  'S4E9 KirShara',
  'S4E10 Daedalus',
  'S4E11 Observer Effect',
  'S4E12 Babel One',
  'S4E13 United',
  'S4E14 The Aenar',
  'S4E15 Affliction',
  'S4E16 Divergence',
  'S4E17 Bound',
  'S4E18 In a Mirror, Darkly (Part I)',
  'S4E19 In a Mirror, Darkly (Part II)',
  'S4E20 Demons',
  'S4E21 Terra Prime',
  'S4E22 These Are the Voyages...'
]

TASepisode = [
  'S1E1 Beyond the Farthest Star',
  'S1E2 Yesteryear',
  'S1E3 One of Our Planets is Missing',
  'S1E4 The Lorelei Signal',
  'S1E5 More Tribbles, More Troubles',
  'S1E6 The Survivor',
  'S1E7 The Infinite Vulcan',
  'S1E8 The Magicks of Megas-tu',
  'S1E9 Once Upon a Planet',
  'S1E10 Mudds Passion',
  'S1E11 The Terratin Incident',
  'S1E12 The Time Trap',
  'S1E13 The Ambergris Element',
  'S1E14 The Slaver Weapon',
  'S1E15 The Eye of the Beholder',
  'S1E16 The Jihad',
  'S2E17 The Pirates of Orion',
  'S2E18 Bem',
  'S2E19 The Practical Joker',
  'S2E20 Albatross',
  'S2E21 How Sharper Than a Serpents Tooth',
  'S2E22 The Counter-Clock Incident'
]

DISEpisode = [
  'S1E1 The Vulcan Hello',
  'S1E2 Battle at the Binary Stars',
  'S1E3 Context is for Kings',
  'S1E4 The Butchers Knife Cares Not for the Lambs Cry',
  'S1E5 Choose Your Pain',
  'S1E6 Lethe',
  'S1E7 Magic to Make the Sanest Man Go Mad',
  'S1E8 Si Vis Pacem, Para Bellum',
  'S1E9 Into the Forest I Go',
  'S1E10 Despite Yourself',
  'S1E11 The Wolf Inside',
  'S1E12 Vaulting Ambition',
  'S1E13 Whats Past Is Prologue',
  'S1E14 The War Without, The War Within',
  'S1E15 Will You Take My Hand?',
  'S2E1 Brother',
  'S2E2 New Eden', 
  'S2E3 Point of Light',
  'S2E4 An Obol for Charon',
  'S2E5 Saints of Imperfection',
  'S2E6 The Sound of Thunder',
  'S2E7 Light and Shadows',
  'S2E8 If Memory Serves',
  'S2E9 Project Daedalus',
  'S2E10 The Red Angel',
  'S2E11 Perpetual Infinity',
  'S2E12 Through the Valley of Shadows',
  'S2E13 Such Sweet Sorrow',
  'S3E1 That Hope Is You, Part 1',
  'S3E2 Far from Home',
  'S3E3 People of Earth',
  'S3E4 Forget Me Not',
  'S3E5 Die Trying',
  'S3E6 Scavengers',
  'S3E7 Unification III',
  'S3E8 The Sanctuary',
  'S3E9 Terra Firma Part 1',
  'S3E10 Terra Firma Part 2',
  'S3E11 SuKal',
  'S3E12 There Is a Tide...',
  'S3E13 That Hope Is You, Part 2'
]

PICEpisode = [
  'S1E1 Remembrance',
  'S1E2 Maps and Legends',
  'S1E3 The End Is the Beginning',
  'S1E4 Absolute Candor',
  'S1E5 Stardust City Rag',
  'S1E6 The Impossible Box',
  'S1E7 Nepenthe',
  'S1E8 Broken Pieces',
  'S1E9 Et in Arcadia Ego, Part 1',
  'S1E10 Et in Arcadia Ego, Part 2'
]

LDEpisode = [
  'S1E1 Second Contact',
  'S1E2 Envoys',
  'S1E3 Temporal Edict',
  'S1E4 Moist Vessel',
  'S1E5 Cupids Errant Arrow',
  'S1E6 Terminal Provocations',
  'S1E7 Much Ado About Boimler',
  'S1E8 Veritas',
  'S1E9 Crisis Point',
  'S1E10 No Small Parts'
]

TNGMovies = [
  'Star Trek Generations',
  'Star Trek First Contact',
  'Star Trek Insurrection',
  'Star Trek Nemesis',
]

TOSMovies = [
  'Star Trek The Motion Picture',
  'Star Trek The Wrath of Khan',
  'Star Trek The Search for Spock',
  'Star Trek The Voyage Home',
  'Star Trek The Final Frontier',
  'Star Trek The Undiscovered Country',
  'Star Trek Generations',
]

RebootMovies = [
  'Star Trek (2009)',
  'Star Trek Into Darkness',
  'Star Trek Beyond'
]

TVMapping = {
    0 : TOSepisode,
    1 : TASepisode,
    2 : TNGepisode,
    3 : DS9episode,
    4 : VOYepisode,
    5 : ENTepisode,
    6 : DISEpisode,
    7 : PICEpisode,
    8 : LDEpisode
}

MovieMapping = {
    0 : TOSMovies,
    1 : TNGMovies,
    2 : RebootMovies
}

repick = ''

while(len(str(repick)) == 0 or repick == 1):
    print("\n\t               .\n\t              .:.\n\t             .:::.\n\t            .:::::.\n\t        ***.:::::::.***\n\t   *******.:::::::::.*******\n\t ********.:::::::::::.********\n\t********.:::::::::::::.********\n\t*******.::::::\'***`::::.*******\n\t******.::::\'*********`::.******\n\t ****.:::\'*************`:.****\n\t   *.::\'*****************`.*\n\t   .:\'  ***************    .\n\t  .\n\t\n\t")
    print('\n\tRandom Star Trek Media Picker')
    
    typeMedia = ''
    while(len(typeMedia) == 0):
        typeMedia = input('\n( 1 ) TV\n( 2 ) Movies\n\nWhat kind of Media? : ')

    typeMedia = int(typeMedia)
    show = ''
    while(len(show) == 0):
        count = 0
        print('')
        if(typeMedia == 1):
          for showtype in series:
              print('(',count,') ',showtype)
              count+=1
        else:
          for showtype in movieSeries:
              print('(',count,') ',showtype)
              count+=1

        show = input('\nWhich show? : ')

    show = int(show)
    repeat = ''
    while(len(str(repeat)) == 0 or repeat == 1 or repeat == 3):
        result = ''
        if(repeat != 3):
          if(typeMedia == 1):
              targetArr = TVMapping.get(show)
              result = targetArr[random.randint(0,len(targetArr)-1)]
              print('\n',result)
          else:
              targetArr = MovieMapping.get(show)
              result = targetArr[random.randint(0,len(targetArr)-1)]
              print('\n',result)
  
        repeat = input('\n( 1 ) Yes\n( 2 ) No\n( 3 ) Open in Browser\n\nRepeat? : ')
        repeat = int(repeat)

        if(repeat == 3):
          webbrowser.open_new_tab('https://www.google.com/search?q='+result.replace(' ','+'))
    
    repick = input('\n( 1 ) Yes\n( 2 ) No\n\nRandomly pick another kind of Star Trek Media? : ')
    repick = int(repick)
